# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Charterer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('switch_board', models.CharField(blank=True, max_length=30)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField(default=0)),
                ('contact_person', models.CharField(blank=True, max_length=250)),
                ('telephone', models.CharField(blank=True, max_length=250)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('telephone', models.CharField(blank=True, max_length=250)),
                ('cons_lad', models.FloatField(blank=True, default=0)),
                ('cons_bal', models.FloatField(blank=True, default=0)),
                ('cons_por_mgo', models.FloatField(blank=True, default=0)),
                ('cons_por_ifo', models.FloatField(blank=True, default=0)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lumpsum', models.FloatField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('days_at_sea', models.FloatField()),
                ('days_in_port', models.FloatField()),
                ('port_disp', models.FloatField()),
                ('misc_exp', models.FloatField()),
                ('comission', models.CharField(default=0, max_length=5)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField()),
                ('deleted', models.BooleanField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoyageCalc.Chart')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoyageCalc.Vessel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='charterer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoyageCalc.Charterer'),
        ),
        migrations.AddField(
            model_name='chart',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chart',
            name='ports',
            field=models.ManyToManyField(to='VoyageCalc.Port'),
        ),
        migrations.AddField(
            model_name='chart',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
