# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoyageCalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='chart',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
