# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoyageCalc', '0002_auto_20170212_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='deleted',
        ),
    ]
