# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoyageCalc', '0002_auto_20170212_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voyage',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='voyage',
            old_name='extra_cost',
            new_name='extra_port_cost',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='voyage_number',
        ),
        migrations.AddField(
            model_name='voyage',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voyage',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voyage',
            name='lumpsum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='port',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='cons_bal',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='cons_lad',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='cons_por_ifo',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='cons_por_mgo',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
