# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoyageCalc', '0003_remove_voyage_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
