# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoyageCalc', '0003_auto_20170212_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='extra_port_cost',
        ),
        migrations.AddField(
            model_name='voyage',
            name='misc_exp',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='voyage',
            name='port_disp',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='days_at_sea',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='days_in_port',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
