# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoyageCalc', '0004_voyage_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyage',
            old_name='days_at_sea',
            new_name='other_inc',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='comission',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='days_in_port',
        ),
        migrations.AddField(
            model_name='vessel',
            name='bunker_price_ifo',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='vessel',
            name='bunker_price_mgo',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='voyage',
            name='days_at_sea_ballast',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='voyage',
            name='days_at_sea_laden',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='voyage',
            name='days_in_port_ifo',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='voyage',
            name='days_in_port_mgo',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
