# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VoyageCalc', '0005_auto_20170212_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voy_updated_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
